name: publicar release en gitbook

#on:
 # release:
 #   types:
   #  - published

jobs:
  sync-to-gitbook:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: 'Ronald-pelaez',
              repo: 'docgit'
            });
            return release.data;
      

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: sincronizar release con gitbook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
        run: |
          release_data=$(echo '${{ steps.get_release.outputs.result }}' | jq -c '.')
          
          response=$(curl -v -X POST https://api.gitbook.com/v1/spaces/$GITBOOK_SPACE_ID/content/import \
            -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "content": {
                "type": "github_release",
                "data": '"$release_data"'
              },
              "source": "website",
              "url": "https://github.com/Ronald-pelaez/docgit/releases"
            }')
          
          echo "Response: $response"
          
          # Check if the response contains an error
          if echo "$response" | grep -q '"error"'; then
            echo "Error in API request"
            exit 1
          fi