name: Sync GitHub Release to GitBook

on:
  repository_dispatch:
    types: [release-published]

jobs:
  sync-to-gitbook:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: 'Ronald-pelaez',
              repo: 'docgit'
            });
            return release.data;

      - name: Sync Release to GitBook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
        run: |
          release_data=$(echo '${{ steps.get_release.outputs.result }}' | jq -c '.')
          
          curl -X POST https://api.gitbook.com/v1/spaces/$GITBOOK_SPACE_ID/content/import \
            -H "Authorization: Bearer GITBOOK_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "content": {
                "type": "github_release",
                "data": '"$release_data"'
              },
              "source": "website",
              "url": "https://github.com/Ronald-pelaez/docgit/blob/main/docs/CHANGELOG.md"
            }'