name: Publish Release to GitBook

on:
  release:
    types: [published]

jobs:
  publish-to-gitbook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Process and Publish to GitBook
        run: |
          # 1. Obtener datos del release
          RELEASE_DATA=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}")
          
          # 2. Extraer información relevante
          TAG_NAME=$(echo "$RELEASE_DATA" | jq -r '.tag_name')
          BODY=$(echo "$RELEASE_DATA" | jq -r '.body')
          
          # 3. Crear contenido en formato Markdown
          MARKDOWN_CONTENT=$(cat << EOF
# Release $TAG_NAME

  $BODY
  EOF
  )
  
  # 4. Crear payload para GitBook
  GITBOOK_PAYLOAD=$(jq -n \
  --arg title "$TAG_NAME" \
  --arg content "$MARKDOWN_CONTENT" \
  '{
"content": {
  "type": "markdown",
  "data": {
    "title": $title,
    "body": $content
  }
}
}')
          
          echo "Payload for GitBook:"
          echo "$GITBOOK_PAYLOAD"
          
          # 5. Enviar a GitBook
          response=$(curl -s -X POST \
            "https://api.gitbook.com/v1/spaces/${{ secrets.GITBOOK_SPACE_ID }}/content/import" \
            -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$GITBOOK_PAYLOAD")
          
          echo "GitBook API Response:"
          echo "$response"
          
          if echo "$response" | jq -e '.error' > /dev/null; then
echo "Error in GitBook API request: $response"
  exit 1
  fi