name: Publish Release to GitBook

on:
  release:
    types: [published]

jobs:
  publish-to-gitbook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Release Info
        id: get_release
        run: |
          RELEASE_JSON=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}")
          
          # Format JSON for GitBook
          GITBOOK_PAYLOAD=$(echo '{
            "importedResources": 1,
            "totalResources": 1,
            "content": {
              "type": "github_release",
              "data": '"$RELEASE_JSON"'
            }
          }' | jq -c '.')
          
          echo "GITBOOK_PAYLOAD<<EOF" >> $GITHUB_ENV
          echo "$GITBOOK_PAYLOAD" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish to GitBook
        run: |
          response=$(curl -s -X POST \
            "https://api.gitbook.com/v1/spaces/${{ secrets.GITBOOK_SPACE_ID }}/content/import" \
            -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$GITBOOK_PAYLOAD")
          
          echo "GitBook API Response: $response"
          
          if echo "$response" | grep -q '"error"'; then
            echo "Error in GitBook API request: $response"
            exit 1
          fi