name: Publish to GitBook

on:
  release:
    types: [published]

jobs:
  publish-to-gitbook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send to GitBook
        run: |
          curl -X POST "https://api.gitbook.com/v1/spaces/${{ secrets.GITBOOK_SPACE_ID }}/content/import" \
          -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "importedResources": 1,
            "totalResources": 1,
            "content": {
              "type": "github_release",
              "data": {
                "source": "website",
                "url": "https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}"
              }
            }
          }'